name: nostr_todo_sdk
description: A Dart SDK for building todo applications with Nostr protocol.
version: 1.1.0
repository: https://github.com/nogringo/nostr-todo-sdk
homepage: https://github.com/nogringo/nostr-todo-sdk

topics:
  - nostr
  - todolist

environment:
  sdk: ^3.8.1

dependencies:
  sembast: ^3.8.5+1
  ndk: ^0.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
